</$objtype/mkfile
LIB=libsed.a
OFILES=alloca.$O btowc.$O dirname-lgpl.$O error.$O exitfail.$O getdelim.$O getline.$O \
	getopt.$O getopt1.$O localcharset.$O lstat.$O mbrlen.$O mbrtowc.$O mbsinit.$O \
	mkstemp.$O obstack.$O quotearg.$O regex.$O rename.$O strerror.$O \
	stripslash.$O strndup.$O strnlen.$O tempname.$O wcrtomb.$O wctob.$O xmalloc.$O \
	xstrndup.$O basename-lgpl.$O strverscmp.$O xalloc-die.$O 

HFILES=../config.h


</sys/src/cmd/mklib

CC=pcc
LD=pcc
CFLAGS=-c -I. -I.. -B -D_POSIX_SOURCE -D_SUSV2_SOURCE \
	-D_EXPERIMENTAL_SOURCE -D_BSD_EXTENSION -D_C99_SNPRINTF_EXTENSION -DHAVE_CONFIG_H \
	-DPLAN9 -DHAVE_ISBLANK -DHAVE_WCTYPE_H -DHAVE_ISWCTYPE -DHAVE_CALLOC 

nuke:V:
	mk clean
	rm -f $LIB
